### ISSUE TITLE
Suggestion: examples folder

### ISSUE THREAD

**Issue by tjansson60** [TaipanRex/pyvisgraph#34]
I was wondering if might be a good idea to have an examples folder in the library showing how to use the package. 

For myself at least I needed write some extra code to use the package to read shapefiles, calculate shortest distance and plot the voyages on maps, so I was thinking that a small examples folder could contain some minimal working examples to do these things just to get users of for a flying start? 

I have examples ready if you are interested I could make a pull-request with these for the project?

Kind regards
Thomas  Jansson

**Comment by TaipanRex** [comment]
I am actually working on full documentation for the package, check out the documentation branch: https://github.com/TaipanRex/pyvisgraph/blob/documentation/docs/user_manual.rst 

Yes I think an examples folder is a good idea, I can then refer to that in the docs.

**Comment by TaipanRex** [comment]
Closed with the merge of #35.
