### ISSUE TITLE
shortest path crossing the obstacle

### ISSUE THREAD

**Issue by EmiliyaHrabova** [TaipanRex/pyvisgraph#42]
_Hi 
I was trying to use the algorithm with shapely polygons.
To pass the points to the graph I'm using polygon.exterior
When I run the algorithm I have the shortest path that is crossing the polygon. Below are the link to the plot and zoom of the area where the path crosses the polygon.
All the land is represented by one polygon, no multipolygons or overlaping polygons.

https://www.dropbox.com/s/rlyxf8e7sw6yn0t/land%20crossing.png?dl=0 (polygon plot with shortest path)
https://www.dropbox.com/s/i6b5ziwplauxqj9/land%20crossing%20zoom.png?dl=0 (zoom)

Any clue how to solve this problem and what am I doing wrong ?_

**SOLVED:
I checked than when you call polygon.exterior you might have points with a huge number of decimal points, so just round the points coordinates to a limited number of decimal points for the coordinates. This solved my problem**

**Comment by TaipanRex** [comment]
Hi, thanks for the update, happy you solved it. Yes, floating point precision can become a problem, check out https://github.com/TaipanRex/pyvisgraph/blob/documentation/docs/user_manual.rst towards the end, "Floating point representation errors". I haven't finished the documentation yet, its on another branch.

**Comment by ekrell** [comment]
Rounding with just round()? Or doing a bit more to control the precision (like the Decimal module)?

I just tried pygraphvis today. Everything runs, but my first test path goes through an obstacle. Could be doing something wrong, but the example code is very straightforward. My only change is that I start with a binary raster -> extract polygons (shapely). Hoping this rounding trick will fix it.

**Comment by eagerbeaver04** [comment]
Does it help you? I tried `pygraphvis` today and have the same problem, but call round() did not help me
