### ISSUE TITLE
is haversine distance in use?

### ISSUE THREAD

**Issue by jannikmi** [TaipanRex/pyvisgraph#43]
Since this package seems to be intended for large scale navigation on earth I wonder if the input polygons are given in (latitude, longitude) coordinates. In that case the distance the actual distance between two points would not be euclidian but the haversine distance right? I am curious how this issue has been incorporated.
I ask because my packages https://github.com/MrMinimal64/extremitypathfinder and https://github.com/MrMinimal64/timezonefinder are related to this issue. Thanks

**Comment by TaipanRex** [comment]
Its not intended for earth navigation, that just happens to be what I used it for originally. Pyvisgraph uses Eucledian distance function. See https://github.com/TaipanRex/pyvisgraph/issues/8.
